name: Commands

on:
  workflow_dispatch:

jobs:
  commands_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[ deprecated ]]; then
            echo "::warning:: Deprecated functionality"
          fi
