name: Commands

on:
  workflow_dispatch:

jobs:
  commands_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[ deprecated ]]; then
            echo "::warning:: Deprecated functionality"
          fi

      - name: Set API Key
        run: echo "API_KEY=12345" >> $GITHUB_ENV

      - name: Use API Key
        run: |
          echo "Using API Key: $API_KEY"