name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Weclome to our first Github Actions Workflow!"

      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: List Repository Files
        run: ls -la
