name: Push and Pull Request Workflow

on:
  push:
    branches:
      - main
      - "release/**"
      - "feature/**"

  pull_request:
    branches:
      - main
      - "release/**"
      - "feature/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Run Tests
        run: npm test
        working-directory: ./src
